# action.yml
name: 'TEI Stylesheets'
description: 'Run using the TEI Stylesheets'
inputs:
  command:  # Command
    description: "Command to run"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}