on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test general docx
        uses: ./ # Uses an action in the root directory
        with:
          command: "docxtotei"
          args: "_test/docxGeneral.docx _output/docxGeneral.xml"
      - name: "Test pure ODD"
        uses: ./
        with:
          command: "teitohtml"
          args: "--odd _test/testPure1.odd _output/teiPure1.html"

      - name: "Test PDF"
        uses: ./
        with:
          command: "teitopdf"
          args: "_test/generalP5.xml _output/generalP5.pdf" 
      # Use the output from the `hello` step
      - name: Check to see what happened
        if: always()
        run: tree
      
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: _output