on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test general docx
        uses: ./
        with:
          command: "docxtotei _test/docxGeneral.docx _output/docxGeneral.xml"
      - name: "Test pure ODD"
        uses: ./
        with:
          command: "teitohtml --odd _test/testPure1.odd _output/teiPure1.html"

      - name: "Test FO"
        uses: ./
        with:
          command: "teitofo _test/generalP5.xml _output/generalP5.fo"
      
      - name: "Test FO to PDF"
        uses: ./
        with:
          command: "fop _output/generalP5.fo _output/generalP5.pdf"

      # Use the output from the `hello` step
      - name: Check to see what happened
        if: always()
        run: tree
      
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: _output